MVCBlog/Controllers/KategoriController.cs
using Blog.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MVCBlog.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        BlogDal BlogIslemleri = new BlogDal();
         
        public ActionResult Kategoriler(int sayfa = 1)
        {
            var Kategoriler = BlogIslemleri.KategorileriListele().ToPagedList(sayfa,5);
            return View(Kategoriler);
        }

        public ActionResult KategoriListele(int id)
        {
            var KategoriID = BlogIslemleri.KategoriIDListele(id);
            return View(KategoriID);
        }

        public PartialViewResult PopulerKategorileriListele()
        {
            var Kategoriler = BlogIslemleri.KategorileriListele().Take(4).ToList();
            return PartialView(Kategoriler);
        }

        public ActionResult KategoriIcerik(int id, int sayfa=1)
        {
            var kategorimakale = BlogIslemleri.MakaleleriListele().OrderBy(x => x.KategoriID).Where(x => x.KategoriID == id).ToPagedList(sayfa, 5);
            return View(kategorimakale);
        }

        
    }
}

MVCBlog/Controllers/MakaleController.cs
using Blog.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MVCBlog.Controllers
{
    public class MakaleController : Controller
    {
        BlogDal BlogIslemleri = new BlogDal(); 

        // GET: Makale
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult MakaleListele()
        {
            var makaleler = BlogIslemleri.MakaleListele();           
            return PartialView(makaleler);
        }

        [HttpGet]
        public ActionResult MakaleGoruntule(int id)
        {
            var userinfo = User.Identity.Name;
            ViewBag.uyeadi = BlogIslemleri.UyeleriListele().Where(x => x.UyeMailAdresi == userinfo).Select(x => x.UyeAdi).FirstOrDefault();
            ViewBag.uyesoyadi = BlogIslemleri.UyeleriListele().Where(x => x.UyeMailAdresi == userinfo).Select(x => x.UyeSoyAdi).FirstOrDefault();
            if (BlogIslemleri.MakaleBul(id) == null)
            {
                return RedirectToAction("Bulunamadi");
            }
            var Makalele = BlogIslemleri.MakaleGoruntule(id);
            Session["Makaleid"] = id;
            return View(Makalele);
        }

        [HttpPost]
        public ActionResult YorumYaz(Yorumlar yeniyorum)
        {
            var urlid = Session["Makaleid"];
            yeniyorum.MakaleID = Convert.ToInt32(urlid);
            BlogIslemleri.YeniYorumOlustur(yeniyorum);
            return RedirectToAction("MakaleGoruntule", new { id = urlid });
        }


        [HttpGet]
        [Authorize(Roles = "Yazar,Admin")]
        public ActionResult MakaleyiGuncelle(int id)
        {
            var guncellenecekmakale = BlogIslemleri.MakaleBul(id);
            return View(guncellenecekmakale);
        }

        [HttpPost]
        [Authorize(Roles = "Yazar,Admin")]
        public ActionResult MakaleyiGuncelle(int id, Makaleler makale)
        {
            BlogIslemleri.MakaleyiGuncelle(id, makale);
            var makaleid = id;
            return RedirectToAction("MakaleGoruntule", "Makale", new { id = makaleid });
        }

        [Authorize(Roles = "Admin")]
        public ActionResult MakaleyiSil(int id)
        {
            BlogIslemleri.MakaleyiSil(id);
            return RedirectToAction("MakaleListele");
        }

        [HttpGet]
        [Authorize(Roles = "Yazar,Admin")]
        public ActionResult MakaleEkle()
        {
            List<SelectListItem> kategori = (from x in BlogIslemleri.KategorileriListele()
                                             select new SelectListItem
                                             {
                                                 Text = x.KategoriAdi,
                                                 Value = x.KategoriID.ToString()
                                             }
                                             ).ToList();
            ViewBag.KategoriListesi = kategori;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Yazar,Admin")]
        public ActionResult MakaleEkle(Makaleler makale)
        {
            makale.YazarID = 6;
            BlogIslemleri.YeniMakaleOlustur(makale);
            var makaleid = makale.MakaleID;
            return RedirectToAction("MakaleGoruntule", new { id = makaleid });
        }

        public PartialViewResult FeaturedMakale()
        {
            var featuremakale = BlogIslemleri.FeaturedMakale();
            return PartialView(featuremakale);
        }

        public PartialViewResult RandomMakale()
        {
            var randommakale = BlogIslemleri.RandomMakale();
            return PartialView(randommakale);
        }

        public PartialViewResult SonMakaleler()
        {
            var sonmakale = BlogIslemleri.MakaleleriListele().OrderByDescending(x => x.MakaleEklenmeTarihi).Take(3).ToList();
            return PartialView(sonmakale);
        }

        public ActionResult Bulunamadi()
        {
            return View();
        }

    }
}

MVCBlog/Controllers/YorumController.cs
using Blog.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Controllers
{
    public class YorumController : Controller
    {
        // GET: Yorum
        BlogDal YorumIslemleri = new BlogDal();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult YorumListele(int id)
        {
            var Yorumlar = YorumIslemleri.YorumlarıListele(id);
            return PartialView(Yorumlar);
        }

        public ActionResult YorumSil(int id)
        {
            var bulunanyorumid = YorumIslemleri.YorumBul(id);
            int makaleid = bulunanyorumid.Select(y => y.MakaleID).FirstOrDefault();
            YorumIslemleri.YorumSil(id);
            return RedirectToAction("MakaleGoruntule", "Makale", new { id = makaleid });
        }
    }
}

MVCBlog/Views/Makale/Bulunamadi.cshtml
@{
    Layout = null;
    ViewBag.Title = "Ana Sayfa";
}



<!DOCTYPE html>
<html lang="en">
<!-- Basic -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site Metas -->
    <title>MVC Blog </title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="~/Theme/images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/Theme/images/apple-touch-icon.png">

    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="~/Theme/css/bootstrap.css" rel="stylesheet">
    <!-- FontAwesome Icons core CSS -->
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Theme/style.css" rel="stylesheet">
    <!-- Responsive styles for this template -->
    <link href="~/Theme/css/responsive.css" rel="stylesheet">
    <!-- Colors for this template -->
    <link href="~/Theme/css/colors.css" rel="stylesheet">
    <!-- Version Garden CSS for this template -->
    <link href="~/Theme/css/version/garden.css" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
    <div id="wrapper">
        @Html.Action("Navbar", "Home");

        <section class="section wb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        Makale Bulunamadı

                    </div><!-- end col -->                    
                </div><!-- end row -->
            </div><!-- end container -->
        </section>



    </div><!-- end wrapper -->
    <!-- Core JavaScript
    ================================================== -->
    <script src="~/Theme/js/jquery.min.js"></script>
    <script src="~/Theme/js/tether.min.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>
    <script src="~/Theme/js/custom.js"></script>
</body>
</html>

MVCBlog/Views/Makale/FeaturedMakale.cshtml
@using Blog.DAL
@model List<Makaleler>



@foreach (var feamakale in Model)
{

    <div class="left-side">
        <div class="masonry-box post-media">
            <img src="@feamakale.MakaleGorsel" alt="" class="img-fluid">
            <div class="shadoweffect">
                <div class="shadow-desc">
                    <div class="blog-meta">
                        <span class="bg-aqua"><a href="/Kategori/KategoriListele/@feamakale.KategoriID" title="">@feamakale.Kategoriler.KategoriAdi</a></span>
                        <h4><a href="/Makale/MakaleGoruntule/@feamakale.MakaleID" title="">@feamakale.MakaleBaslikAdi</a></h4>
                        <small><a href="/Makale/MakaleGoruntule/@feamakale.MakaleID" title="">@feamakale.MakaleEklenmeTarihi</a></small>
                        <small><a href="/Yazar/YazarGoruntule/@feamakale.YazarID" title="">@feamakale.Yazarlar.YazarAdi</a></small>
                    </div><!-- end meta -->
                </div><!-- end shadow-desc -->
            </div><!-- end shadow -->
        </div><!-- end post-media -->
    </div><!-- end left-side -->
}

MVCBlog/Views/Makale/MakaleEkle.cshtml
@model Blog.DAL.Makaleler
@{
    ViewBag.Title = "MakaleEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>MakaleEkle</h2>

@using (Html.BeginForm("MakaleEkle", "Makale", FormMethod.Post))
{
    @Html.Label("Makale Başlığı")
    @Html.TextBoxFor(x => x.MakaleBaslikAdi, new { @class = "form-control" })
    <br />
    @Html.Label("Makale Kategorisi")
    @Html.DropDownListFor(x => x.KategoriID, (List<SelectListItem>)ViewBag.KategoriListesi, new { @class = "form-control" })
    <br />
    @Html.Label("Makale Görseli")
    @Html.TextBoxFor(x => x.MakaleGorsel, new { @class = "form-control"})
    <br />
    @Html.Label("Makale İçeriği")
    @Html.TextAreaFor(x => x.MakaleIcerik, new { @class = "form-control" })
    <br />
    <button type="submit" class="btn btn-success">Makale Ekle</button>
}

MVCBlog/Views/Makale/MakaleGoruntule.cshtml
@using Blog.DAL
@model List<Makaleler>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site Metas -->
    <title>MVC Blog - Makale İçerik</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="~/Theme/css/bootstrap.css" rel="stylesheet">
    <!-- FontAwesome Icons core CSS -->
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Theme/style.css" rel="stylesheet">
    <!-- Responsive styles for this template -->
    <link href="~/Theme/css/responsive.css" rel="stylesheet">
    <!-- Colors for this template -->
    <link href="css/colors.css" rel="stylesheet">
    <!-- Version Garden CSS for this template -->
    <link href="~/Theme/css/version/garden.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
    @Html.Action("Navbar","Home")
       
        <section class="section wb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            @foreach (var makale in Model)
                            {
                                <div class="blog-title-area">
                                    <span class="color-green"><a href="garden-category.html" title="">@makale.Kategoriler.KategoriAdi</a></span>
                                    <h3>@makale.MakaleBaslikAdi</h3>
                                    <div class="blog-meta big-meta">
                                        <small><a href="garden-single.html" title="">@makale.MakaleEklenmeTarihi</a></small>
                                        <small><a href="blog-author.html" title="">@makale.Yazarlar.YazarAdi</a></small>
                                        @*<small><a href="#" title=""><i class="fa fa-eye"></i> 2344</a></small>*@
                                    </div><!-- end meta -->
                                </div><!-- end title makale.Resimlers.Where(x => x.MakaleID == makale.MakaleID).Select(x => x.ResimURL).FirstOrDefault() -->
                                <div class="single-post-media">
                                    <img src="@makale.MakaleGorsel" alt="" class="img-fluid">
                                </div><!-- end media -->
                                <div class="blog-content">
                                    <div class="pp">
                                        <p>@makale.MakaleIcerik</p>
                                    </div><!-- end pp -->

                                </div><!-- end content -->

                                <section class="section wb" />
                                <div class="custombox authorbox clearfix">
                                    <h4 class="small-title">Yazar Hakkında</h4>
                                    <div class="row">
                                        <!-- end col -->
                                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                                            <h4><a href="#">@makale.Yazarlar.YazarAdi @makale.Yazarlar.YazarSoyAdi</a></h4>
                                            <p>@makale.Yazarlar.YazarMailAdresi</p>
                                            <div class="topsocial">
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Youtube"><i class="fa fa-youtube"></i></a>
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Website"><i class="fa fa-link"></i></a>
                                            </div><!-- end social -->
                                        </div><!-- end col -->
                                    </div><!-- end row -->
                                </div><!-- end author-box -->
                                <hr class="invis1">
                                @Html.Action("RandomMakale", "Makale")
                                <hr class="invis1">
                                <div class="custombox clearfix">
                                    <h4 class="small-title">Yorumlar</h4>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="comments-list">
                                                @Html.Action("YorumListele", "Yorum")
                                            </div>
                                        </div><!-- end col -->
                                    </div><!-- end row -->
                                </div><!-- end custom-box -->
                                <hr class="invis1">
                                <div class="custombox clearfix">
                                    <h4 class="small-title">Yorum Bırak</h4>
                                    <div class="row">
                                        <div class="col-lg-12">

                                            @using (Html.BeginForm("YorumYaz", "Makale", FormMethod.Post, new { @class = "form-wrapper" }))
                                            {
                                                if (User.Identity.IsAuthenticated == true)
                                                {

                                                    <input type="text" name="YorumYazanAdiSoyadi" class="form-control" value="@ViewBag.uyeadi @ViewBag.uyesoyadi">
                                                }
                                                else
                                                {
                                                    <input type="text" name="YorumYazanAdiSoyadi" class="form-control" placeholder="Adınız Soyadınız">
                                                }

                                                <textarea class="form-control" name="YorumAciklama" placeholder="Yorumunuz"></textarea>
                                                <button type="submit" class="btn btn-primary">Yorumu Gönder</button>
                                            }
                                        </div>
                                    </div>
                                </div>
                            }
                        </div><!-- end page-wrapper -->
                    </div><!-- end col -->
                    <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">
                            <div class="widget">
                                <h2 class="widget-title">Önceki Makaleler</h2>
                                <div class="blog-list-widget">
                                    @Html.Action("SonMakaleler", "Makale")


                                </div><!-- end blog-list -->
                            </div><!-- end widget -->
                            @Html.Action("PopulerKategorileriListele", "Kategori")
                        </div><!-- end sidebar -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        </section>
    </div><!-- end wrapper -->
    <!-- Core JavaScript
    ================================================== -->
    <script src="~/Theme/js/jquery.min.js"></script>
    <script src="~/Theme/js/tether.min.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>
    <script src="~/Theme/js/custom.js"></script>
</body>
</html>

MVCBlog/Views/Makale/MakaleListele.cshtml
@using Blog.DAL
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Makaleler>

@foreach (var makaleliste in Model)
{
    <div class="page-wrapper">
        <div class="blog-list clearfix">
            <div class="blog-box row">
                <div class="col-md-4">
                    <div class="post-media">
                        <a href="/Makale/MakaleGoruntule/@makaleliste.MakaleID" title="">
                            <img src="@makaleliste.MakaleGorsel" alt="" class="img-fluid">
                            <div class="hovereffect"></div>
                        </a>
                    </div><!-- end media -->
                </div><!-- end col -->
                <div class="blog-meta big-meta col-md-8">
                    <span class="bg-aqua"><a href="/Makale/MakaleGoruntule/@makaleliste.MakaleID" title="">@makaleliste.Kategoriler.KategoriAdi</a></span>
                    <h4><a href="/Makale/MakaleGoruntule/@makaleliste.MakaleID" title="">@makaleliste.MakaleBaslikAdi</a></h4>
                    <p>@makaleliste.MakaleIcerik.Substring(0, 150) ...</p>
                    @*<small><a href="garden-category.html" title=""><i class="fa fa-eye"></i> 1887</a></small>*@
                    <small>@makaleliste.MakaleEklenmeTarihi</small>
                    <small><a href="/Yazar/YazarGoruntule/@makaleliste.YazarID" title="">@makaleliste.Yazarlar.YazarAdi</a></small>
                </div><!-- end meta -->
            </div><!-- end blog-box -->
            <hr class="invis">
        </div><!-- end blog-list -->
    </div>

}
<hr class="invis">
<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-start">
                @Html.PagedListPager(Model, sayfa => Url.Action("Index", "Home", new { sayfa }), new PagedListRenderOptions
           {
               
               LiElementClasses = new List<string>
               { "page-link"}
           })
            </ul>
        </nav>
    </div><!-- end col -->
</div>

MVCBlog/Views/Makale/MakaleyiGuncelle.cshtml
@model Blog.DAL.Makaleler


@{
    ViewBag.Title = "MakaleyiGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>MakaleyiGuncelle</h2>

@using (Html.BeginForm("MakaleyiGuncelle", "Makale", FormMethod.Post))
{
    <form>
        @Html.HiddenFor(x => x.MakaleID)
        @Html.HiddenFor(x => x.KategoriID)
        @Html.HiddenFor(x => x.YazarID)
        @*@Html.Label("Kategori")
            @Html.TextBoxFor(x => x.KategoriID, new { @readonly = "readonly", @class = "form-control" })
            <br />
            @Html.Label("Yazar")
            @Html.TextBoxFor(x => x.YazarID, new { @readonly = "readonly", @class = "form-control" })
            <br />*@
        @Html.Label("Makale Başlığı")
        @Html.TextBoxFor(x => x.MakaleBaslikAdi, new { @class = "form-control" })
        <br />
        @Html.Label("Makale Görseli")
        @Html.TextBoxFor(x => x.MakaleGorsel, new { @class = "form-control" })
        <br />
        @Html.Label("Makale İçeriği")
        @Html.TextAreaFor(x => x.MakaleIcerik, new { @class = "form-control" })
        <br />
        <button type="submit">Güncelle</button>


    </form>

}

MVCBlog/Views/Makale/RandomMakale.cshtml
@using Blog.DAL
@model List<Makaleler>


<div class="custombox clearfix">
    <h4 class="small-title">Bunlarada Gözatabilirsiniz</h4>
    <div class="row">
        @foreach (var randommakale in Model)
        {
            <div class="col-lg-6">
                <div class="blog-box">
                    <div class="post-media">
                        <a href="/Makale/MakaleGoruntule/@randommakale.MakaleID" title="">
                            <img src="@randommakale.MakaleGorsel" alt="" class="img-fluid">
                            <div class="hovereffect">
                                <span class=""></span>
                            </div><!-- end hover -->
                        </a>
                    </div><!-- end media -->
                    <div class="blog-meta">
                        <h4><a href="/Makale/MakaleGoruntule/@randommakale.MakaleID" title="">@randommakale.MakaleBaslikAdi</a></h4>
                        <small><a href="/Kategori/KategoriListele/@randommakale.KategoriID" title="">@randommakale.Kategoriler.KategoriAdi</a></small>
                        <small>@randommakale.MakaleEklenmeTarihi</small>
                    </div><!-- end meta -->
                </div><!-- end blog-box -->
            </div>
        }<!-- end col -->
    </div><!-- end row -->
</div><!-- end custom-box -->

MVCBlog/Views/Makale/SonMakaleler.cshtml
@using Blog.DAL
@model List<Makaleler>

@foreach (var sonmakaleler in Model)

{
    <div class="list-group">
        <a href="/Makale/MakaleGoruntule/@sonmakaleler.MakaleID" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="w-100 justify-content-between">

                <img src="@sonmakaleler.MakaleGorsel" alt="" class="img-fluid float-left">
                <h5 class="mb-1">@sonmakaleler.MakaleBaslikAdi</h5>
                <h5 class="mb-1">@sonmakaleler.Kategoriler.KategoriAdi</h5>
                <small>@sonmakaleler.MakaleEklenmeTarihi</small>
            </div>
        </a>
    </div>
}